/**
 * Unified CRM schema definitions.
 *
 * A Contact can appear in multiple sources. The unified record links them all.
 * An Interaction is any message/conversation event from any source.
 */

/**
 * Create a blank unified contact record.
 * @param {string} id  - stable unique id (generated by merge.js)
 */
function createContact(id) {
    return {
        id,                // e.g. "c_001"
        name: null,        // best known display name
        phones: [],        // ["+447..."]
        emails: [],        // ["foo@example.com"]
        notes: null,       // freeform notes
        tags: [],          // ["investor", "friend"]
        sources: {
            whatsapp: null,        // { id, number, isMyContact, isBusiness, about, profilePic }
            linkedin: null,        // { name, email, company, position, connectedOn, profileUrl }
            telegram: null,        // { userId, name, phone }
            email: null,           // { email, name, firstSeen }
            googleContacts: null,  // { name, phones, emails, org, title, note, birthday }
            sms: null,             // { phone, contactName, messageCount, lastMessageAt }
            slack: null,           // { id, userId, name, displayName, title, workspace }
            discord: null,         // { id, name, discordRef, messageCount, lastMessageAt }
            imessage: null,        // { id, name, imessageRef, messageCount, lastMessageAt }
        },
        lastContactedAt: null,   // ISO timestamp of most recent interaction
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };
}

/**
 * Create a unified interaction record from a raw message.
 * @param {string} source  - "whatsapp" | "linkedin" | "telegram" | "email"
 * @param {object} raw     - source-specific message object
 */
function countStructuredCollection(raw, keys) {
    for (const key of keys) {
        const value = raw[key];
        if (Array.isArray(value)) return value.length;
        if (Number.isInteger(value) && value > 0) return value;
    }
    return 0;
}

function buildInteractionMetadata(raw = {}) {
    const metadata = {};

    if (raw.hasAttachment === true || raw.hasAttachments === true || raw.attachmentCount > 0 || raw.attachmentsCount > 0 || Array.isArray(raw.attachments) && raw.attachments.length > 0 || raw.attachment) {
        metadata.hasAttachment = true;
    }

    const linkPreviewCount = countStructuredCollection(raw, ['linkPreviews', 'link_preview', 'linkPreviewsCount', 'linkPreviewCount']);
    if (linkPreviewCount > 0) metadata.linkPreviewCount = linkPreviewCount;

    const reactionCount = countStructuredCollection(raw, ['reactions', 'reactionCount', 'reactionsCount']);
    if (reactionCount > 0) metadata.reactionCount = reactionCount;

    return metadata;
}

function createInteraction(source, raw) {
    return {
        id: raw.id || null,
        source,
        timestamp: raw.timestamp || raw.date || null,
        from: raw.from || null,
        to: raw.to || null,
        body: raw.body || raw.text || raw.content || null,
        subject: raw.subject || null,         // email / LinkedIn InMail
        chatId: raw.chatId || raw.conversationId || null,
        chatName: raw.chatName || null,
        type: raw.type || 'message',
        metadata: buildInteractionMetadata(raw),
        raw,                                  // keep original for reference
    };
}

module.exports = { createContact, createInteraction, buildInteractionMetadata };
